### ISSUE TITLE
Library does not load

### ISSUE THREAD

**Issue by RafaelBarbosatec** [RobertApikyan/LifecycleEvents#1]
Gradle APPLICATION:
repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }

Gradle APP:
implementation 'com.github.RobertApikyan:LifecycleEvents:0.0.1'

ERROR:
Error:(29, 20) Failed to resolve: com.github.RobertApikyan:LifecycleEvents:0.0.1
<a href="openFile:/Users/rafael/Documents/Estudos/MyApplication/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by RobertApikyan** [comment]
I have just added the library to the new project and it works, can you provide some additional information. Can you provide your Android Studio version and Gradle version 

![image](https://user-images.githubusercontent.com/17802092/44264567-222a5980-a234-11e8-96be-e0b133a3732a.png)

![image](https://user-images.githubusercontent.com/17802092/44264595-3e2dfb00-a234-11e8-887a-0be5992e2a7f.png)

**Comment by RobertApikyan** [comment]
Error:(29, 20) indicate that maven { url 'https://jitpack.io' }  is not added , make sure that you have added maven { url 'https://jitpack.io' } to you project level gradle file

I will close the issue, but feel free to reopen it if problem still exist
